//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modulecapabilities

import mock "github.com/stretchr/testify/mock"

// MockModuleHasAltNames is an autogenerated mock type for the ModuleHasAltNames type
type MockModuleHasAltNames struct {
	mock.Mock
}

type MockModuleHasAltNames_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModuleHasAltNames) EXPECT() *MockModuleHasAltNames_Expecter {
	return &MockModuleHasAltNames_Expecter{mock: &_m.Mock}
}

// AltNames provides a mock function with given fields:
func (_m *MockModuleHasAltNames) AltNames() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AltNames")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockModuleHasAltNames_AltNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AltNames'
type MockModuleHasAltNames_AltNames_Call struct {
	*mock.Call
}

// AltNames is a helper method to define mock.On call
func (_e *MockModuleHasAltNames_Expecter) AltNames() *MockModuleHasAltNames_AltNames_Call {
	return &MockModuleHasAltNames_AltNames_Call{Call: _e.mock.On("AltNames")}
}

func (_c *MockModuleHasAltNames_AltNames_Call) Run(run func()) *MockModuleHasAltNames_AltNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModuleHasAltNames_AltNames_Call) Return(_a0 []string) *MockModuleHasAltNames_AltNames_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModuleHasAltNames_AltNames_Call) RunAndReturn(run func() []string) *MockModuleHasAltNames_AltNames_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModuleHasAltNames creates a new instance of MockModuleHasAltNames. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModuleHasAltNames(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModuleHasAltNames {
	mock := &MockModuleHasAltNames{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
