//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modulecapabilities

import mock "github.com/stretchr/testify/mock"

// MockTextTransform is an autogenerated mock type for the TextTransform type
type MockTextTransform struct {
	mock.Mock
}

type MockTextTransform_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTextTransform) EXPECT() *MockTextTransform_Expecter {
	return &MockTextTransform_Expecter{mock: &_m.Mock}
}

// Transform provides a mock function with given fields: in
func (_m *MockTextTransform) Transform(in []string) ([]string, error) {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]string, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTextTransform_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type MockTextTransform_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - in []string
func (_e *MockTextTransform_Expecter) Transform(in interface{}) *MockTextTransform_Transform_Call {
	return &MockTextTransform_Transform_Call{Call: _e.mock.On("Transform", in)}
}

func (_c *MockTextTransform_Transform_Call) Run(run func(in []string)) *MockTextTransform_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockTextTransform_Transform_Call) Return(_a0 []string, _a1 error) *MockTextTransform_Transform_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTextTransform_Transform_Call) RunAndReturn(run func([]string) ([]string, error)) *MockTextTransform_Transform_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTextTransform creates a new instance of MockTextTransform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTextTransform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTextTransform {
	mock := &MockTextTransform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
