//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modulecapabilities

import (
	context "context"

	additional "github.com/weaviate/weaviate/entities/additional"

	mock "github.com/stretchr/testify/mock"

	models "github.com/weaviate/weaviate/entities/models"

	moduletools "github.com/weaviate/weaviate/entities/moduletools"

	search "github.com/weaviate/weaviate/entities/search"

	strfmt "github.com/go-openapi/strfmt"
)

// MockReferenceVectorizer is an autogenerated mock type for the ReferenceVectorizer type
type MockReferenceVectorizer struct {
	mock.Mock
}

type MockReferenceVectorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReferenceVectorizer) EXPECT() *MockReferenceVectorizer_Expecter {
	return &MockReferenceVectorizer_Expecter{mock: &_m.Mock}
}

// VectorizeObject provides a mock function with given fields: ctx, object, cfg, findObjectFn
func (_m *MockReferenceVectorizer) VectorizeObject(ctx context.Context, object *models.Object, cfg moduletools.ClassConfig, findObjectFn func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)) ([]float32, error) {
	ret := _m.Called(ctx, object, cfg, findObjectFn)

	if len(ret) == 0 {
		panic("no return value specified for VectorizeObject")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Object, moduletools.ClassConfig, func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)) ([]float32, error)); ok {
		return rf(ctx, object, cfg, findObjectFn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Object, moduletools.ClassConfig, func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)) []float32); ok {
		r0 = rf(ctx, object, cfg, findObjectFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Object, moduletools.ClassConfig, func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)) error); ok {
		r1 = rf(ctx, object, cfg, findObjectFn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReferenceVectorizer_VectorizeObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VectorizeObject'
type MockReferenceVectorizer_VectorizeObject_Call struct {
	*mock.Call
}

// VectorizeObject is a helper method to define mock.On call
//   - ctx context.Context
//   - object *models.Object
//   - cfg moduletools.ClassConfig
//   - findObjectFn func(context.Context , string , strfmt.UUID , search.SelectProperties , additional.Properties , string)(*search.Result , error)
func (_e *MockReferenceVectorizer_Expecter) VectorizeObject(ctx interface{}, object interface{}, cfg interface{}, findObjectFn interface{}) *MockReferenceVectorizer_VectorizeObject_Call {
	return &MockReferenceVectorizer_VectorizeObject_Call{Call: _e.mock.On("VectorizeObject", ctx, object, cfg, findObjectFn)}
}

func (_c *MockReferenceVectorizer_VectorizeObject_Call) Run(run func(ctx context.Context, object *models.Object, cfg moduletools.ClassConfig, findObjectFn func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error))) *MockReferenceVectorizer_VectorizeObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Object), args[2].(moduletools.ClassConfig), args[3].(func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)))
	})
	return _c
}

func (_c *MockReferenceVectorizer_VectorizeObject_Call) Return(_a0 []float32, _a1 error) *MockReferenceVectorizer_VectorizeObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReferenceVectorizer_VectorizeObject_Call) RunAndReturn(run func(context.Context, *models.Object, moduletools.ClassConfig, func(context.Context, string, strfmt.UUID, search.SelectProperties, additional.Properties, string) (*search.Result, error)) ([]float32, error)) *MockReferenceVectorizer_VectorizeObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReferenceVectorizer creates a new instance of MockReferenceVectorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReferenceVectorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReferenceVectorizer {
	mock := &MockReferenceVectorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
