//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modulecapabilities

import mock "github.com/stretchr/testify/mock"

// MockTextTransformers is an autogenerated mock type for the TextTransformers type
type MockTextTransformers struct {
	mock.Mock
}

type MockTextTransformers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTextTransformers) EXPECT() *MockTextTransformers_Expecter {
	return &MockTextTransformers_Expecter{mock: &_m.Mock}
}

// TextTransformers provides a mock function with given fields:
func (_m *MockTextTransformers) TextTransformers() map[string]TextTransform {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TextTransformers")
	}

	var r0 map[string]TextTransform
	if rf, ok := ret.Get(0).(func() map[string]TextTransform); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]TextTransform)
		}
	}

	return r0
}

// MockTextTransformers_TextTransformers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TextTransformers'
type MockTextTransformers_TextTransformers_Call struct {
	*mock.Call
}

// TextTransformers is a helper method to define mock.On call
func (_e *MockTextTransformers_Expecter) TextTransformers() *MockTextTransformers_TextTransformers_Call {
	return &MockTextTransformers_TextTransformers_Call{Call: _e.mock.On("TextTransformers")}
}

func (_c *MockTextTransformers_TextTransformers_Call) Run(run func()) *MockTextTransformers_TextTransformers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTextTransformers_TextTransformers_Call) Return(_a0 map[string]TextTransform) *MockTextTransformers_TextTransformers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTextTransformers_TextTransformers_Call) RunAndReturn(run func() map[string]TextTransform) *MockTextTransformers_TextTransformers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTextTransformers creates a new instance of MockTextTransformers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTextTransformers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTextTransformers {
	mock := &MockTextTransformers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
