//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modulecapabilities

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Vectorizers provides a mock function with given fields:
func (_m *MockClient) Vectorizers() map[string]VectorizerClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Vectorizers")
	}

	var r0 map[string]VectorizerClient
	if rf, ok := ret.Get(0).(func() map[string]VectorizerClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]VectorizerClient)
		}
	}

	return r0
}

// MockClient_Vectorizers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Vectorizers'
type MockClient_Vectorizers_Call struct {
	*mock.Call
}

// Vectorizers is a helper method to define mock.On call
func (_e *MockClient_Expecter) Vectorizers() *MockClient_Vectorizers_Call {
	return &MockClient_Vectorizers_Call{Call: _e.mock.On("Vectorizers")}
}

func (_c *MockClient_Vectorizers_Call) Run(run func()) *MockClient_Vectorizers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Vectorizers_Call) Return(_a0 map[string]VectorizerClient) *MockClient_Vectorizers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Vectorizers_Call) RunAndReturn(run func() map[string]VectorizerClient) *MockClient_Vectorizers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
