//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package schema

import (
	middleware "github.com/go-openapi/runtime/middleware"
	mock "github.com/stretchr/testify/mock"

	models "github.com/weaviate/weaviate/entities/models"
)

// MockSchemaObjectsUpdateHandler is an autogenerated mock type for the SchemaObjectsUpdateHandler type
type MockSchemaObjectsUpdateHandler struct {
	mock.Mock
}

type MockSchemaObjectsUpdateHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemaObjectsUpdateHandler) EXPECT() *MockSchemaObjectsUpdateHandler_Expecter {
	return &MockSchemaObjectsUpdateHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *MockSchemaObjectsUpdateHandler) Handle(_a0 SchemaObjectsUpdateParams, _a1 *models.Principal) middleware.Responder {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(SchemaObjectsUpdateParams, *models.Principal) middleware.Responder); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// MockSchemaObjectsUpdateHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockSchemaObjectsUpdateHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 SchemaObjectsUpdateParams
//   - _a1 *models.Principal
func (_e *MockSchemaObjectsUpdateHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}) *MockSchemaObjectsUpdateHandler_Handle_Call {
	return &MockSchemaObjectsUpdateHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *MockSchemaObjectsUpdateHandler_Handle_Call) Run(run func(_a0 SchemaObjectsUpdateParams, _a1 *models.Principal)) *MockSchemaObjectsUpdateHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SchemaObjectsUpdateParams), args[1].(*models.Principal))
	})
	return _c
}

func (_c *MockSchemaObjectsUpdateHandler_Handle_Call) Return(_a0 middleware.Responder) *MockSchemaObjectsUpdateHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchemaObjectsUpdateHandler_Handle_Call) RunAndReturn(run func(SchemaObjectsUpdateParams, *models.Principal) middleware.Responder) *MockSchemaObjectsUpdateHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchemaObjectsUpdateHandler creates a new instance of MockSchemaObjectsUpdateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemaObjectsUpdateHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemaObjectsUpdateHandler {
	mock := &MockSchemaObjectsUpdateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
