//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package lsmkv

import (
	mock "github.com/stretchr/testify/mock"
	sroar "github.com/weaviate/sroar"
)

// MockCursorRoaringSet is an autogenerated mock type for the CursorRoaringSet type
type MockCursorRoaringSet struct {
	mock.Mock
}

type MockCursorRoaringSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCursorRoaringSet) EXPECT() *MockCursorRoaringSet_Expecter {
	return &MockCursorRoaringSet_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockCursorRoaringSet) Close() {
	_m.Called()
}

// MockCursorRoaringSet_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCursorRoaringSet_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCursorRoaringSet_Expecter) Close() *MockCursorRoaringSet_Close_Call {
	return &MockCursorRoaringSet_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCursorRoaringSet_Close_Call) Run(run func()) *MockCursorRoaringSet_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCursorRoaringSet_Close_Call) Return() *MockCursorRoaringSet_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCursorRoaringSet_Close_Call) RunAndReturn(run func()) *MockCursorRoaringSet_Close_Call {
	_c.Call.Return(run)
	return _c
}

// First provides a mock function with given fields:
func (_m *MockCursorRoaringSet) First() ([]byte, *sroar.Bitmap) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 []byte
	var r1 *sroar.Bitmap
	if rf, ok := ret.Get(0).(func() ([]byte, *sroar.Bitmap)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() *sroar.Bitmap); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sroar.Bitmap)
		}
	}

	return r0, r1
}

// MockCursorRoaringSet_First_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'First'
type MockCursorRoaringSet_First_Call struct {
	*mock.Call
}

// First is a helper method to define mock.On call
func (_e *MockCursorRoaringSet_Expecter) First() *MockCursorRoaringSet_First_Call {
	return &MockCursorRoaringSet_First_Call{Call: _e.mock.On("First")}
}

func (_c *MockCursorRoaringSet_First_Call) Run(run func()) *MockCursorRoaringSet_First_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCursorRoaringSet_First_Call) Return(_a0 []byte, _a1 *sroar.Bitmap) *MockCursorRoaringSet_First_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCursorRoaringSet_First_Call) RunAndReturn(run func() ([]byte, *sroar.Bitmap)) *MockCursorRoaringSet_First_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with given fields:
func (_m *MockCursorRoaringSet) Next() ([]byte, *sroar.Bitmap) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 []byte
	var r1 *sroar.Bitmap
	if rf, ok := ret.Get(0).(func() ([]byte, *sroar.Bitmap)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() *sroar.Bitmap); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sroar.Bitmap)
		}
	}

	return r0, r1
}

// MockCursorRoaringSet_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockCursorRoaringSet_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockCursorRoaringSet_Expecter) Next() *MockCursorRoaringSet_Next_Call {
	return &MockCursorRoaringSet_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockCursorRoaringSet_Next_Call) Run(run func()) *MockCursorRoaringSet_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCursorRoaringSet_Next_Call) Return(_a0 []byte, _a1 *sroar.Bitmap) *MockCursorRoaringSet_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCursorRoaringSet_Next_Call) RunAndReturn(run func() ([]byte, *sroar.Bitmap)) *MockCursorRoaringSet_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: _a0
func (_m *MockCursorRoaringSet) Seek(_a0 []byte) ([]byte, *sroar.Bitmap) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 []byte
	var r1 *sroar.Bitmap
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, *sroar.Bitmap)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) *sroar.Bitmap); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*sroar.Bitmap)
		}
	}

	return r0, r1
}

// MockCursorRoaringSet_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockCursorRoaringSet_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockCursorRoaringSet_Expecter) Seek(_a0 interface{}) *MockCursorRoaringSet_Seek_Call {
	return &MockCursorRoaringSet_Seek_Call{Call: _e.mock.On("Seek", _a0)}
}

func (_c *MockCursorRoaringSet_Seek_Call) Run(run func(_a0 []byte)) *MockCursorRoaringSet_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockCursorRoaringSet_Seek_Call) Return(_a0 []byte, _a1 *sroar.Bitmap) *MockCursorRoaringSet_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCursorRoaringSet_Seek_Call) RunAndReturn(run func([]byte) ([]byte, *sroar.Bitmap)) *MockCursorRoaringSet_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCursorRoaringSet creates a new instance of MockCursorRoaringSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCursorRoaringSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCursorRoaringSet {
	mock := &MockCursorRoaringSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
