//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package clusterapi

import mock "github.com/stretchr/testify/mock"

// Mockdb is an autogenerated mock type for the db type
type Mockdb struct {
	mock.Mock
}

type Mockdb_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockdb) EXPECT() *Mockdb_Expecter {
	return &Mockdb_Expecter{mock: &_m.Mock}
}

// StartupComplete provides a mock function with given fields:
func (_m *Mockdb) StartupComplete() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartupComplete")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Mockdb_StartupComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartupComplete'
type Mockdb_StartupComplete_Call struct {
	*mock.Call
}

// StartupComplete is a helper method to define mock.On call
func (_e *Mockdb_Expecter) StartupComplete() *Mockdb_StartupComplete_Call {
	return &Mockdb_StartupComplete_Call{Call: _e.mock.On("StartupComplete")}
}

func (_c *Mockdb_StartupComplete_Call) Run(run func()) *Mockdb_StartupComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockdb_StartupComplete_Call) Return(_a0 bool) *Mockdb_StartupComplete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockdb_StartupComplete_Call) RunAndReturn(run func() bool) *Mockdb_StartupComplete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdb creates a new instance of Mockdb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdb(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockdb {
	mock := &Mockdb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
