//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package classification

import mock "github.com/stretchr/testify/mock"

// MocktfidfScorer is an autogenerated mock type for the tfidfScorer type
type MocktfidfScorer struct {
	mock.Mock
}

type MocktfidfScorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktfidfScorer) EXPECT() *MocktfidfScorer_Expecter {
	return &MocktfidfScorer_Expecter{mock: &_m.Mock}
}

// GetAllTerms provides a mock function with given fields: docIndex
func (_m *MocktfidfScorer) GetAllTerms(docIndex int) []TermWithTfIdf {
	ret := _m.Called(docIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTerms")
	}

	var r0 []TermWithTfIdf
	if rf, ok := ret.Get(0).(func(int) []TermWithTfIdf); ok {
		r0 = rf(docIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TermWithTfIdf)
		}
	}

	return r0
}

// MocktfidfScorer_GetAllTerms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTerms'
type MocktfidfScorer_GetAllTerms_Call struct {
	*mock.Call
}

// GetAllTerms is a helper method to define mock.On call
//   - docIndex int
func (_e *MocktfidfScorer_Expecter) GetAllTerms(docIndex interface{}) *MocktfidfScorer_GetAllTerms_Call {
	return &MocktfidfScorer_GetAllTerms_Call{Call: _e.mock.On("GetAllTerms", docIndex)}
}

func (_c *MocktfidfScorer_GetAllTerms_Call) Run(run func(docIndex int)) *MocktfidfScorer_GetAllTerms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MocktfidfScorer_GetAllTerms_Call) Return(_a0 []TermWithTfIdf) *MocktfidfScorer_GetAllTerms_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocktfidfScorer_GetAllTerms_Call) RunAndReturn(run func(int) []TermWithTfIdf) *MocktfidfScorer_GetAllTerms_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocktfidfScorer creates a new instance of MocktfidfScorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktfidfScorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktfidfScorer {
	mock := &MocktfidfScorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
