//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package rest

import (
	mock "github.com/stretchr/testify/mock"
	graphql "github.com/weaviate/weaviate/adapters/handlers/graphql"
)

// MockgraphQLProvider is an autogenerated mock type for the graphQLProvider type
type MockgraphQLProvider struct {
	mock.Mock
}

type MockgraphQLProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockgraphQLProvider) EXPECT() *MockgraphQLProvider_Expecter {
	return &MockgraphQLProvider_Expecter{mock: &_m.Mock}
}

// GetGraphQL provides a mock function with given fields:
func (_m *MockgraphQLProvider) GetGraphQL() graphql.GraphQL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGraphQL")
	}

	var r0 graphql.GraphQL
	if rf, ok := ret.Get(0).(func() graphql.GraphQL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graphql.GraphQL)
		}
	}

	return r0
}

// MockgraphQLProvider_GetGraphQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraphQL'
type MockgraphQLProvider_GetGraphQL_Call struct {
	*mock.Call
}

// GetGraphQL is a helper method to define mock.On call
func (_e *MockgraphQLProvider_Expecter) GetGraphQL() *MockgraphQLProvider_GetGraphQL_Call {
	return &MockgraphQLProvider_GetGraphQL_Call{Call: _e.mock.On("GetGraphQL")}
}

func (_c *MockgraphQLProvider_GetGraphQL_Call) Run(run func()) *MockgraphQLProvider_GetGraphQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockgraphQLProvider_GetGraphQL_Call) Return(_a0 graphql.GraphQL) *MockgraphQLProvider_GetGraphQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockgraphQLProvider_GetGraphQL_Call) RunAndReturn(run func() graphql.GraphQL) *MockgraphQLProvider_GetGraphQL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockgraphQLProvider creates a new instance of MockgraphQLProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockgraphQLProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockgraphQLProvider {
	mock := &MockgraphQLProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
