//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package traverser

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/weaviate/weaviate/entities/dto"

	search "github.com/weaviate/weaviate/entities/search"
)

// Mockexplorer is an autogenerated mock type for the explorer type
type Mockexplorer struct {
	mock.Mock
}

type Mockexplorer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockexplorer) EXPECT() *Mockexplorer_Expecter {
	return &Mockexplorer_Expecter{mock: &_m.Mock}
}

// CrossClassVectorSearch provides a mock function with given fields: ctx, params
func (_m *Mockexplorer) CrossClassVectorSearch(ctx context.Context, params ExploreParams) ([]search.Result, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CrossClassVectorSearch")
	}

	var r0 []search.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ExploreParams) ([]search.Result, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ExploreParams) []search.Result); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]search.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ExploreParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockexplorer_CrossClassVectorSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CrossClassVectorSearch'
type Mockexplorer_CrossClassVectorSearch_Call struct {
	*mock.Call
}

// CrossClassVectorSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - params ExploreParams
func (_e *Mockexplorer_Expecter) CrossClassVectorSearch(ctx interface{}, params interface{}) *Mockexplorer_CrossClassVectorSearch_Call {
	return &Mockexplorer_CrossClassVectorSearch_Call{Call: _e.mock.On("CrossClassVectorSearch", ctx, params)}
}

func (_c *Mockexplorer_CrossClassVectorSearch_Call) Run(run func(ctx context.Context, params ExploreParams)) *Mockexplorer_CrossClassVectorSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ExploreParams))
	})
	return _c
}

func (_c *Mockexplorer_CrossClassVectorSearch_Call) Return(_a0 []search.Result, _a1 error) *Mockexplorer_CrossClassVectorSearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockexplorer_CrossClassVectorSearch_Call) RunAndReturn(run func(context.Context, ExploreParams) ([]search.Result, error)) *Mockexplorer_CrossClassVectorSearch_Call {
	_c.Call.Return(run)
	return _c
}

// GetClass provides a mock function with given fields: ctx, params
func (_m *Mockexplorer) GetClass(ctx context.Context, params dto.GetParams) ([]interface{}, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetClass")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetParams) ([]interface{}, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetParams) []interface{}); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Mockexplorer_GetClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClass'
type Mockexplorer_GetClass_Call struct {
	*mock.Call
}

// GetClass is a helper method to define mock.On call
//   - ctx context.Context
//   - params dto.GetParams
func (_e *Mockexplorer_Expecter) GetClass(ctx interface{}, params interface{}) *Mockexplorer_GetClass_Call {
	return &Mockexplorer_GetClass_Call{Call: _e.mock.On("GetClass", ctx, params)}
}

func (_c *Mockexplorer_GetClass_Call) Run(run func(ctx context.Context, params dto.GetParams)) *Mockexplorer_GetClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.GetParams))
	})
	return _c
}

func (_c *Mockexplorer_GetClass_Call) Return(_a0 []interface{}, _a1 error) *Mockexplorer_GetClass_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Mockexplorer_GetClass_Call) RunAndReturn(run func(context.Context, dto.GetParams) ([]interface{}, error)) *Mockexplorer_GetClass_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockexplorer creates a new instance of Mockexplorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockexplorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockexplorer {
	mock := &Mockexplorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
