//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package roaringset

import (
	mock "github.com/stretchr/testify/mock"
	segmentindex "github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex"
)

// MockSeeker is an autogenerated mock type for the Seeker type
type MockSeeker struct {
	mock.Mock
}

type MockSeeker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeeker) EXPECT() *MockSeeker_Expecter {
	return &MockSeeker_Expecter{mock: &_m.Mock}
}

// Seek provides a mock function with given fields: key
func (_m *MockSeeker) Seek(key []byte) (segmentindex.Node, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 segmentindex.Node
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (segmentindex.Node, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func([]byte) segmentindex.Node); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(segmentindex.Node)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSeeker_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockSeeker_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - key []byte
func (_e *MockSeeker_Expecter) Seek(key interface{}) *MockSeeker_Seek_Call {
	return &MockSeeker_Seek_Call{Call: _e.mock.On("Seek", key)}
}

func (_c *MockSeeker_Seek_Call) Run(run func(key []byte)) *MockSeeker_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockSeeker_Seek_Call) Return(_a0 segmentindex.Node, _a1 error) *MockSeeker_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSeeker_Seek_Call) RunAndReturn(run func([]byte) (segmentindex.Node, error)) *MockSeeker_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeeker creates a new instance of MockSeeker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeeker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeeker {
	mock := &MockSeeker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
