//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package vectorizer

import mock "github.com/stretchr/testify/mock"

// MockClassSettings is an autogenerated mock type for the ClassSettings type
type MockClassSettings struct {
	mock.Mock
}

type MockClassSettings_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassSettings) EXPECT() *MockClassSettings_Expecter {
	return &MockClassSettings_Expecter{mock: &_m.Mock}
}

// ImageField provides a mock function with given fields: property
func (_m *MockClassSettings) ImageField(property string) bool {
	ret := _m.Called(property)

	if len(ret) == 0 {
		panic("no return value specified for ImageField")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(property)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClassSettings_ImageField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageField'
type MockClassSettings_ImageField_Call struct {
	*mock.Call
}

// ImageField is a helper method to define mock.On call
//   - property string
func (_e *MockClassSettings_Expecter) ImageField(property interface{}) *MockClassSettings_ImageField_Call {
	return &MockClassSettings_ImageField_Call{Call: _e.mock.On("ImageField", property)}
}

func (_c *MockClassSettings_ImageField_Call) Run(run func(property string)) *MockClassSettings_ImageField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClassSettings_ImageField_Call) Return(_a0 bool) *MockClassSettings_ImageField_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClassSettings_ImageField_Call) RunAndReturn(run func(string) bool) *MockClassSettings_ImageField_Call {
	_c.Call.Return(run)
	return _c
}

// ImageFieldsWeights provides a mock function with given fields:
func (_m *MockClassSettings) ImageFieldsWeights() ([]float32, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ImageFieldsWeights")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]float32, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []float32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClassSettings_ImageFieldsWeights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageFieldsWeights'
type MockClassSettings_ImageFieldsWeights_Call struct {
	*mock.Call
}

// ImageFieldsWeights is a helper method to define mock.On call
func (_e *MockClassSettings_Expecter) ImageFieldsWeights() *MockClassSettings_ImageFieldsWeights_Call {
	return &MockClassSettings_ImageFieldsWeights_Call{Call: _e.mock.On("ImageFieldsWeights")}
}

func (_c *MockClassSettings_ImageFieldsWeights_Call) Run(run func()) *MockClassSettings_ImageFieldsWeights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClassSettings_ImageFieldsWeights_Call) Return(_a0 []float32, _a1 error) *MockClassSettings_ImageFieldsWeights_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClassSettings_ImageFieldsWeights_Call) RunAndReturn(run func() ([]float32, error)) *MockClassSettings_ImageFieldsWeights_Call {
	_c.Call.Return(run)
	return _c
}

// InferenceURL provides a mock function with given fields:
func (_m *MockClassSettings) InferenceURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InferenceURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockClassSettings_InferenceURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InferenceURL'
type MockClassSettings_InferenceURL_Call struct {
	*mock.Call
}

// InferenceURL is a helper method to define mock.On call
func (_e *MockClassSettings_Expecter) InferenceURL() *MockClassSettings_InferenceURL_Call {
	return &MockClassSettings_InferenceURL_Call{Call: _e.mock.On("InferenceURL")}
}

func (_c *MockClassSettings_InferenceURL_Call) Run(run func()) *MockClassSettings_InferenceURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClassSettings_InferenceURL_Call) Return(_a0 string) *MockClassSettings_InferenceURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClassSettings_InferenceURL_Call) RunAndReturn(run func() string) *MockClassSettings_InferenceURL_Call {
	_c.Call.Return(run)
	return _c
}

// TextField provides a mock function with given fields: property
func (_m *MockClassSettings) TextField(property string) bool {
	ret := _m.Called(property)

	if len(ret) == 0 {
		panic("no return value specified for TextField")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(property)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClassSettings_TextField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TextField'
type MockClassSettings_TextField_Call struct {
	*mock.Call
}

// TextField is a helper method to define mock.On call
//   - property string
func (_e *MockClassSettings_Expecter) TextField(property interface{}) *MockClassSettings_TextField_Call {
	return &MockClassSettings_TextField_Call{Call: _e.mock.On("TextField", property)}
}

func (_c *MockClassSettings_TextField_Call) Run(run func(property string)) *MockClassSettings_TextField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClassSettings_TextField_Call) Return(_a0 bool) *MockClassSettings_TextField_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClassSettings_TextField_Call) RunAndReturn(run func(string) bool) *MockClassSettings_TextField_Call {
	_c.Call.Return(run)
	return _c
}

// TextFieldsWeights provides a mock function with given fields:
func (_m *MockClassSettings) TextFieldsWeights() ([]float32, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TextFieldsWeights")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]float32, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []float32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClassSettings_TextFieldsWeights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TextFieldsWeights'
type MockClassSettings_TextFieldsWeights_Call struct {
	*mock.Call
}

// TextFieldsWeights is a helper method to define mock.On call
func (_e *MockClassSettings_Expecter) TextFieldsWeights() *MockClassSettings_TextFieldsWeights_Call {
	return &MockClassSettings_TextFieldsWeights_Call{Call: _e.mock.On("TextFieldsWeights")}
}

func (_c *MockClassSettings_TextFieldsWeights_Call) Run(run func()) *MockClassSettings_TextFieldsWeights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClassSettings_TextFieldsWeights_Call) Return(_a0 []float32, _a1 error) *MockClassSettings_TextFieldsWeights_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClassSettings_TextFieldsWeights_Call) RunAndReturn(run func() ([]float32, error)) *MockClassSettings_TextFieldsWeights_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClassSettings creates a new instance of MockClassSettings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassSettings(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassSettings {
	mock := &MockClassSettings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
