//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package models

import mock "github.com/stretchr/testify/mock"

// MockSchemaHistory is an autogenerated mock type for the SchemaHistory type
type MockSchemaHistory struct {
	mock.Mock
}

type MockSchemaHistory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemaHistory) EXPECT() *MockSchemaHistory_Expecter {
	return &MockSchemaHistory_Expecter{mock: &_m.Mock}
}

// NewMockSchemaHistory creates a new instance of MockSchemaHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemaHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemaHistory {
	mock := &MockSchemaHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
