//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package cluster

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRemote is an autogenerated mock type for the Remote type
type MockRemote struct {
	mock.Mock
}

type MockRemote_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemote) EXPECT() *MockRemote_Expecter {
	return &MockRemote_Expecter{mock: &_m.Mock}
}

// BroadcastAbortTransaction provides a mock function with given fields: ctx, tx
func (_m *MockRemote) BroadcastAbortTransaction(ctx context.Context, tx *Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastAbortTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemote_BroadcastAbortTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastAbortTransaction'
type MockRemote_BroadcastAbortTransaction_Call struct {
	*mock.Call
}

// BroadcastAbortTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *Transaction
func (_e *MockRemote_Expecter) BroadcastAbortTransaction(ctx interface{}, tx interface{}) *MockRemote_BroadcastAbortTransaction_Call {
	return &MockRemote_BroadcastAbortTransaction_Call{Call: _e.mock.On("BroadcastAbortTransaction", ctx, tx)}
}

func (_c *MockRemote_BroadcastAbortTransaction_Call) Run(run func(ctx context.Context, tx *Transaction)) *MockRemote_BroadcastAbortTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Transaction))
	})
	return _c
}

func (_c *MockRemote_BroadcastAbortTransaction_Call) Return(_a0 error) *MockRemote_BroadcastAbortTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemote_BroadcastAbortTransaction_Call) RunAndReturn(run func(context.Context, *Transaction) error) *MockRemote_BroadcastAbortTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastCommitTransaction provides a mock function with given fields: ctx, tx
func (_m *MockRemote) BroadcastCommitTransaction(ctx context.Context, tx *Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastCommitTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemote_BroadcastCommitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastCommitTransaction'
type MockRemote_BroadcastCommitTransaction_Call struct {
	*mock.Call
}

// BroadcastCommitTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *Transaction
func (_e *MockRemote_Expecter) BroadcastCommitTransaction(ctx interface{}, tx interface{}) *MockRemote_BroadcastCommitTransaction_Call {
	return &MockRemote_BroadcastCommitTransaction_Call{Call: _e.mock.On("BroadcastCommitTransaction", ctx, tx)}
}

func (_c *MockRemote_BroadcastCommitTransaction_Call) Run(run func(ctx context.Context, tx *Transaction)) *MockRemote_BroadcastCommitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Transaction))
	})
	return _c
}

func (_c *MockRemote_BroadcastCommitTransaction_Call) Return(_a0 error) *MockRemote_BroadcastCommitTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemote_BroadcastCommitTransaction_Call) RunAndReturn(run func(context.Context, *Transaction) error) *MockRemote_BroadcastCommitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastTransaction provides a mock function with given fields: ctx, tx
func (_m *MockRemote) BroadcastTransaction(ctx context.Context, tx *Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemote_BroadcastTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastTransaction'
type MockRemote_BroadcastTransaction_Call struct {
	*mock.Call
}

// BroadcastTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *Transaction
func (_e *MockRemote_Expecter) BroadcastTransaction(ctx interface{}, tx interface{}) *MockRemote_BroadcastTransaction_Call {
	return &MockRemote_BroadcastTransaction_Call{Call: _e.mock.On("BroadcastTransaction", ctx, tx)}
}

func (_c *MockRemote_BroadcastTransaction_Call) Run(run func(ctx context.Context, tx *Transaction)) *MockRemote_BroadcastTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Transaction))
	})
	return _c
}

func (_c *MockRemote_BroadcastTransaction_Call) Return(_a0 error) *MockRemote_BroadcastTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemote_BroadcastTransaction_Call) RunAndReturn(run func(context.Context, *Transaction) error) *MockRemote_BroadcastTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemote creates a new instance of MockRemote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemote(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemote {
	mock := &MockRemote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
