//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package cluster

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommitFn is an autogenerated mock type for the CommitFn type
type MockCommitFn struct {
	mock.Mock
}

type MockCommitFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitFn) EXPECT() *MockCommitFn_Expecter {
	return &MockCommitFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, tx
func (_m *MockCommitFn) Execute(ctx context.Context, tx *Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommitFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommitFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *Transaction
func (_e *MockCommitFn_Expecter) Execute(ctx interface{}, tx interface{}) *MockCommitFn_Execute_Call {
	return &MockCommitFn_Execute_Call{Call: _e.mock.On("Execute", ctx, tx)}
}

func (_c *MockCommitFn_Execute_Call) Run(run func(ctx context.Context, tx *Transaction)) *MockCommitFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Transaction))
	})
	return _c
}

func (_c *MockCommitFn_Execute_Call) Return(_a0 error) *MockCommitFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommitFn_Execute_Call) RunAndReturn(run func(context.Context, *Transaction) error) *MockCommitFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommitFn creates a new instance of MockCommitFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitFn {
	mock := &MockCommitFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
