//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package memwatch

import mock "github.com/stretchr/testify/mock"

// MockmetricsReader is an autogenerated mock type for the metricsReader type
type MockmetricsReader struct {
	mock.Mock
}

type MockmetricsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmetricsReader) EXPECT() *MockmetricsReader_Expecter {
	return &MockmetricsReader_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *MockmetricsReader) Execute() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockmetricsReader_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockmetricsReader_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockmetricsReader_Expecter) Execute() *MockmetricsReader_Execute_Call {
	return &MockmetricsReader_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockmetricsReader_Execute_Call) Run(run func()) *MockmetricsReader_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockmetricsReader_Execute_Call) Return(_a0 int64) *MockmetricsReader_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmetricsReader_Execute_Call) RunAndReturn(run func() int64) *MockmetricsReader_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmetricsReader creates a new instance of MockmetricsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmetricsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmetricsReader {
	mock := &MockmetricsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
