//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package diskio

import mock "github.com/stretchr/testify/mock"

// MockMeteredReaderCallback is an autogenerated mock type for the MeteredReaderCallback type
type MockMeteredReaderCallback struct {
	mock.Mock
}

type MockMeteredReaderCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMeteredReaderCallback) EXPECT() *MockMeteredReaderCallback_Expecter {
	return &MockMeteredReaderCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: read, nanoseconds
func (_m *MockMeteredReaderCallback) Execute(read int64, nanoseconds int64) {
	_m.Called(read, nanoseconds)
}

// MockMeteredReaderCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockMeteredReaderCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - read int64
//   - nanoseconds int64
func (_e *MockMeteredReaderCallback_Expecter) Execute(read interface{}, nanoseconds interface{}) *MockMeteredReaderCallback_Execute_Call {
	return &MockMeteredReaderCallback_Execute_Call{Call: _e.mock.On("Execute", read, nanoseconds)}
}

func (_c *MockMeteredReaderCallback_Execute_Call) Run(run func(read int64, nanoseconds int64)) *MockMeteredReaderCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *MockMeteredReaderCallback_Execute_Call) Return() *MockMeteredReaderCallback_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMeteredReaderCallback_Execute_Call) RunAndReturn(run func(int64, int64)) *MockMeteredReaderCallback_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMeteredReaderCallback creates a new instance of MockMeteredReaderCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMeteredReaderCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMeteredReaderCallback {
	mock := &MockMeteredReaderCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
