//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockVectorizerValidator is an autogenerated mock type for the VectorizerValidator type
type MockVectorizerValidator struct {
	mock.Mock
}

type MockVectorizerValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVectorizerValidator) EXPECT() *MockVectorizerValidator_Expecter {
	return &MockVectorizerValidator_Expecter{mock: &_m.Mock}
}

// ValidateVectorizer provides a mock function with given fields: moduleName
func (_m *MockVectorizerValidator) ValidateVectorizer(moduleName string) error {
	ret := _m.Called(moduleName)

	if len(ret) == 0 {
		panic("no return value specified for ValidateVectorizer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(moduleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVectorizerValidator_ValidateVectorizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateVectorizer'
type MockVectorizerValidator_ValidateVectorizer_Call struct {
	*mock.Call
}

// ValidateVectorizer is a helper method to define mock.On call
//   - moduleName string
func (_e *MockVectorizerValidator_Expecter) ValidateVectorizer(moduleName interface{}) *MockVectorizerValidator_ValidateVectorizer_Call {
	return &MockVectorizerValidator_ValidateVectorizer_Call{Call: _e.mock.On("ValidateVectorizer", moduleName)}
}

func (_c *MockVectorizerValidator_ValidateVectorizer_Call) Run(run func(moduleName string)) *MockVectorizerValidator_ValidateVectorizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockVectorizerValidator_ValidateVectorizer_Call) Return(_a0 error) *MockVectorizerValidator_ValidateVectorizer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVectorizerValidator_ValidateVectorizer_Call) RunAndReturn(run func(string) error) *MockVectorizerValidator_ValidateVectorizer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVectorizerValidator creates a new instance of MockVectorizerValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVectorizerValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVectorizerValidator {
	mock := &MockVectorizerValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
