//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package modrerankercohere

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	ent "github.com/weaviate/weaviate/usecases/modulecomponents/ent"

	moduletools "github.com/weaviate/weaviate/entities/moduletools"
)

// MockReRankerCohereClient is an autogenerated mock type for the ReRankerCohereClient type
type MockReRankerCohereClient struct {
	mock.Mock
}

type MockReRankerCohereClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReRankerCohereClient) EXPECT() *MockReRankerCohereClient_Expecter {
	return &MockReRankerCohereClient_Expecter{mock: &_m.Mock}
}

// MetaInfo provides a mock function with given fields:
func (_m *MockReRankerCohereClient) MetaInfo() (map[string]interface{}, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetaInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReRankerCohereClient_MetaInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetaInfo'
type MockReRankerCohereClient_MetaInfo_Call struct {
	*mock.Call
}

// MetaInfo is a helper method to define mock.On call
func (_e *MockReRankerCohereClient_Expecter) MetaInfo() *MockReRankerCohereClient_MetaInfo_Call {
	return &MockReRankerCohereClient_MetaInfo_Call{Call: _e.mock.On("MetaInfo")}
}

func (_c *MockReRankerCohereClient_MetaInfo_Call) Run(run func()) *MockReRankerCohereClient_MetaInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReRankerCohereClient_MetaInfo_Call) Return(_a0 map[string]interface{}, _a1 error) *MockReRankerCohereClient_MetaInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReRankerCohereClient_MetaInfo_Call) RunAndReturn(run func() (map[string]interface{}, error)) *MockReRankerCohereClient_MetaInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Rank provides a mock function with given fields: ctx, query, documents, cfg
func (_m *MockReRankerCohereClient) Rank(ctx context.Context, query string, documents []string, cfg moduletools.ClassConfig) (*ent.RankResult, error) {
	ret := _m.Called(ctx, query, documents, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Rank")
	}

	var r0 *ent.RankResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, moduletools.ClassConfig) (*ent.RankResult, error)); ok {
		return rf(ctx, query, documents, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, moduletools.ClassConfig) *ent.RankResult); ok {
		r0 = rf(ctx, query, documents, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.RankResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, moduletools.ClassConfig) error); ok {
		r1 = rf(ctx, query, documents, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReRankerCohereClient_Rank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rank'
type MockReRankerCohereClient_Rank_Call struct {
	*mock.Call
}

// Rank is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - documents []string
//   - cfg moduletools.ClassConfig
func (_e *MockReRankerCohereClient_Expecter) Rank(ctx interface{}, query interface{}, documents interface{}, cfg interface{}) *MockReRankerCohereClient_Rank_Call {
	return &MockReRankerCohereClient_Rank_Call{Call: _e.mock.On("Rank", ctx, query, documents, cfg)}
}

func (_c *MockReRankerCohereClient_Rank_Call) Run(run func(ctx context.Context, query string, documents []string, cfg moduletools.ClassConfig)) *MockReRankerCohereClient_Rank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].(moduletools.ClassConfig))
	})
	return _c
}

func (_c *MockReRankerCohereClient_Rank_Call) Return(_a0 *ent.RankResult, _a1 error) *MockReRankerCohereClient_Rank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReRankerCohereClient_Rank_Call) RunAndReturn(run func(context.Context, string, []string, moduletools.ClassConfig) (*ent.RankResult, error)) *MockReRankerCohereClient_Rank_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReRankerCohereClient creates a new instance of MockReRankerCohereClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReRankerCohereClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReRankerCohereClient {
	mock := &MockReRankerCohereClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
