//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package aggregate

import (
	mock "github.com/stretchr/testify/mock"
	aggregation "github.com/weaviate/weaviate/entities/aggregation"
)

// MocktextExtractorFunc is an autogenerated mock type for the textExtractorFunc type
type MocktextExtractorFunc struct {
	mock.Mock
}

type MocktextExtractorFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktextExtractorFunc) EXPECT() *MocktextExtractorFunc_Expecter {
	return &MocktextExtractorFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MocktextExtractorFunc) Execute(_a0 aggregation.Text) (interface{}, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(aggregation.Text) (interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(aggregation.Text) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(aggregation.Text) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocktextExtractorFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MocktextExtractorFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 aggregation.Text
func (_e *MocktextExtractorFunc_Expecter) Execute(_a0 interface{}) *MocktextExtractorFunc_Execute_Call {
	return &MocktextExtractorFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MocktextExtractorFunc_Execute_Call) Run(run func(_a0 aggregation.Text)) *MocktextExtractorFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(aggregation.Text))
	})
	return _c
}

func (_c *MocktextExtractorFunc_Execute_Call) Return(_a0 interface{}, _a1 error) *MocktextExtractorFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocktextExtractorFunc_Execute_Call) RunAndReturn(run func(aggregation.Text) (interface{}, error)) *MocktextExtractorFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocktextExtractorFunc creates a new instance of MocktextExtractorFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktextExtractorFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktextExtractorFunc {
	mock := &MocktextExtractorFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
