//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package aggregate

import (
	mock "github.com/stretchr/testify/mock"
	aggregation "github.com/weaviate/weaviate/entities/aggregation"
)

// MockbooleanExtractorFunc is an autogenerated mock type for the booleanExtractorFunc type
type MockbooleanExtractorFunc struct {
	mock.Mock
}

type MockbooleanExtractorFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbooleanExtractorFunc) EXPECT() *MockbooleanExtractorFunc_Expecter {
	return &MockbooleanExtractorFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockbooleanExtractorFunc) Execute(_a0 aggregation.Boolean) interface{} {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(aggregation.Boolean) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockbooleanExtractorFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockbooleanExtractorFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 aggregation.Boolean
func (_e *MockbooleanExtractorFunc_Expecter) Execute(_a0 interface{}) *MockbooleanExtractorFunc_Execute_Call {
	return &MockbooleanExtractorFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockbooleanExtractorFunc_Execute_Call) Run(run func(_a0 aggregation.Boolean)) *MockbooleanExtractorFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(aggregation.Boolean))
	})
	return _c
}

func (_c *MockbooleanExtractorFunc_Execute_Call) Return(_a0 interface{}) *MockbooleanExtractorFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockbooleanExtractorFunc_Execute_Call) RunAndReturn(run func(aggregation.Boolean) interface{}) *MockbooleanExtractorFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbooleanExtractorFunc creates a new instance of MockbooleanExtractorFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbooleanExtractorFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbooleanExtractorFunc {
	mock := &MockbooleanExtractorFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
