//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2024 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by mockery v2.43.2. DO NOT EDIT.

package hnsw

import mock "github.com/stretchr/testify/mock"

// MockMakeCommitLogger is an autogenerated mock type for the MakeCommitLogger type
type MockMakeCommitLogger struct {
	mock.Mock
}

type MockMakeCommitLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMakeCommitLogger) EXPECT() *MockMakeCommitLogger_Expecter {
	return &MockMakeCommitLogger_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *MockMakeCommitLogger) Execute() (CommitLogger, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 CommitLogger
	var r1 error
	if rf, ok := ret.Get(0).(func() (CommitLogger, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() CommitLogger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CommitLogger)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMakeCommitLogger_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockMakeCommitLogger_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockMakeCommitLogger_Expecter) Execute() *MockMakeCommitLogger_Execute_Call {
	return &MockMakeCommitLogger_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockMakeCommitLogger_Execute_Call) Run(run func()) *MockMakeCommitLogger_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMakeCommitLogger_Execute_Call) Return(_a0 CommitLogger, _a1 error) *MockMakeCommitLogger_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMakeCommitLogger_Execute_Call) RunAndReturn(run func() (CommitLogger, error)) *MockMakeCommitLogger_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMakeCommitLogger creates a new instance of MockMakeCommitLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMakeCommitLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMakeCommitLogger {
	mock := &MockMakeCommitLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
